        <link type="text/css" rel="stylesheet" href="css/smoothness/jquery-ui-1.10.0.custom.css"/>
        <link type="text/css" rel="stylesheet" href="css/layout-default-latest.css"/>
        <link type="text/css" rel="stylesheet" href="css/fiddler.css"/>
        <script type="text/javascript" src="js/ace/ace.js"></script>
        <script type="text/javascript" src="js/jquery-1.9.0.js"></script>
        <script type="text/javascript" src="js/jquery-ui-1.10.0.custom.js"></script>
        <script type="text/javascript" src="js/jquery.layout-latest.js"></script>
        <script type="text/javascript" src="js/fiddler.js"></script>

